import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "/",
    title: "Home",
    icon: "mdi mdi-home-variant",
    class: "submenu-title",
    extralink: false,
    submenu: [],
  },
  // {
  //   path: "",
  //   title: "Reports",
  //   icon: "mdi mdi-chart-line",
  //   class: "nav-small-cap",
  //   extralink: false,
  //   submenu: [
      {
        title: "Sales Reports",
        icon: "mdi mdi-file-chart",
        class: "submenu-title",
        extralink: false,
        path: null,
        submenu: [
          {
            path: "/starter",
            title: "Sales Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: "/monthlyProductSaleModule",
            title: "Product Sale Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: "/gemsalesreport",
            title: "Gem Sale Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
        ],
      },
      {
        title: "Financial Reports",
        icon: "mdi mdi-cash-multiple",
        class: "submenu-title",
        extralink: false,
        path: null,
        submenu: [
          {
            path: "/cashBank",
            title: "Cash Bank",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: "/dailyCashCollection",
            title: "Cash Collection Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: "/monthlyBalanceReport",
            title: "Balance Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: "/monthlySchemeMaturity",
            title: "Scheme Maturity Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
        ],
      },
      {
        title: "Inventory Reports",
        icon: "mdi mdi-chart-line",
        class: "submenu-title",
        extralink: false,
        path: null,
        submenu: [
          {
            path: "/branchStockReport",
            title: "Branch Stock Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: "/metalBalance",
            title: "Metal Balance Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: null,
            title: "Stock Order Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: "/oldGold",
            title: "Old Gold Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
        ],
      },
      {
        title: "Customer Reports",
        icon: "mdi mdi-account-multiple",
        class: "submenu-title",
        extralink: false,
        path: null,
        submenu: [
          {
            path: "/customerdata",
            title: "Customer Data Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: null,
            title: "Sundry Creditors Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
        ],
      },
      {
        title: "Operational Reports",
        icon: "mdi mdi-chart-bar",
        class: "submenu-title",
        extralink: false,
        path: null,
        submenu: [
          {
            path: "/frontPosition",
            title: "Front Position",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: null,
            title: "Smith Position Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: null,
            title: "Daliy Note Report",
            icon: "mdi mdi-note-text",
            class: "",
            extralink: false,
            submenu: [],
          },
        ],
      },
  //   ],
  // }
  
  // {
  //   path: "",
  //   title: "Reports",
  //   icon: "mdi mdi-chart-line",
  //   class: "nav-small-cap",

  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/branchStockReport",
  //       title: "Branch Stock Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/cashBank",
  //       title: "Cash Bank",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/customerdata",
  //       title: "Customer Data report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/dailyCashCollection",
  //       title: "Daily Cash Collection Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: null,
  //       title: "Daliy Note Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/starter",
  //       title: "Daily Sales Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/frontPosition",
  //       title: "Front Position",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/gemsalesreport",
  //       title: "Gem Sale Report ",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/metalBalance",
  //       title: "Metal Balance Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/monthlyBalanceReport",
  //       title: "Monthly Balance Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/monthlyProductSaleModule",
  //       title: "Monthly ProductSale Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/monthlySchemeMaturity",
  //       title: "Monthly SchemeMaturity Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/oldGold",
  //       title: "Old Gold Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  
  //     {
  //       path: null,
  //       title: "Smith Position Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: null,
  //       title: " Stock Order Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: null,
  //       title: " Sundry Creditors Report",
  //       icon: "mdi mdi-note-text",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     }
  //   ]
    

  // },
  // {
  //   path: "/starter",
  //   title: "Daily Sales",
  //   icon: "mdi mdi-shopping",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/dailynotes",
  //   title: "Daily Notes",
  //   icon: "mdi mdi-note-text",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: '/sale-analytics',
  //   title: 'Sale Analytics',
  //   icon: 'mdi mdi-chart-bubble',
  //   class: '',
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: '/sale-analytics/gold',
  //       title: 'Gold Sale',
  //       icon: 'mdi mdi-database',
  //       class: '',
  //       extralink: false,
  //       submenu: []
  //     },
  //     {
  //       path: '/sale-analytics/gem',
  //       title: 'Gem Sale',
  //       icon: 'mdi mdi-diamond',
  //       class: '',
  //       extralink: false,
  //       submenu: []
  //     }
  //   ]
  // },
];
